### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by dmatuschek** [PantelisGeorgiadis/dcmjs-dimse#17]
Do you plan to provide Typescript interfaces? (For example by porting the project to Typescript or by adding types to "definitely typed").
I think this is by far the most convenient DICOM package for JS, which is why I would love to see TS support.

Thanks for your work!

**Comment by PantelisGeorgiadis** [comment]
Hello David! Thank you for your kind comments! Typescript support was in my list but now that I know that there's at least one person needs it, it will move up in priority!

**Comment by andreidubov** [comment]
Hi @PantelisGeorgiadis, thank you for the great work!

It would be great if typescript support is added. We are also waiting for this, thanks for raising the priority.

**Comment by PantelisGeorgiadis** [comment]
Hello @andreidubov! Thank you for your kind comment!
It is definitely in my highest priorities! Hope to find the needed time soon!
Any PRs or contributions would be greatly appreciated!

**Comment by PantelisGeorgiadis** [comment]
Hello @dmatuschek!
Thank you for your awesome work! I guess my response (https://github.com/PantelisGeorgiadis/dcmjs-dimse/issues/17#issuecomment-1155062520), regarding providing typescript support, was totally misleading… ☹
All I meant was that it is in my list to provide typescript types (i.e. an index.d.ts file) and not move the whole project to typescript, which, I haven’t used in any of my other projects.

Can we somehow keep both worlds (JS and TS) in an easy and maintainable way?

**Comment by dmatuschek** [comment]
Oh, that's unfortunate. Anyway, I think keeping both versions is not a good idea. I would suggest reverting all changes and creating a type file. I will do this as soon as I can.

**Comment by PantelisGeorgiadis** [comment]
Thank you @dmatuschek and sorry for the misunderstanding! We are looking forward for your type file PR!

**Comment by PantelisGeorgiadis** [comment]
Hello @dmatuschek and @andreidubov!
Latest release (v0.1.7) contains typescript type declarations! I would be grateful if you could check them out and provide feedback.
