### ISSUE TITLE
Upgrade dcmjs dependency

### ISSUE THREAD

**Issue by richard-viney** [PantelisGeorgiadis/dcmjs-dimse#19]
Could the dcmjs dependency be upgraded to "^0.24.1" in the package.json so all the recent fixes are included?

Thanks!

**Comment by richard-viney** [comment]
Thanks, would it be possible to do an NPM release that includes this change?

**Comment by PantelisGeorgiadis** [comment]
Done! `lockfileVersion` was reverted back to 1 by my npm (probably older version) but I don't believe that this is going to be an issue.
