### ISSUE TITLE
is a good native dicom program

### ISSUE THREAD

**Issue by CloudWoR** [PantelisGeorgiadis/dcmjs-dimse#2]
I want to use nodejs to realize the film printing function of DICOM. Is it feasible？

**Comment by CloudWoR** [comment]
Thank you very much for your contributions to the JS implementation of DICOM protocol

**Comment by PantelisGeorgiadis** [comment]
@CloudWoR, v0.0.8 has been pushed to master and it now contains full support for all N-SERVICES. You can now build your film printing functions!
