### ISSUE TITLE
Error encoding ‘Latin1’

### ISSUE THREAD

**Issue by ledinhthi** [PantelisGeorgiadis/dcmjs-dimse#26]
I got this error when i intergrate javascript node into mobile react native so i can’t get worklist

**Comment by PantelisGeorgiadis** [comment]
Hello @ledinhthi! Thanks for reporting this. Could you please share any stack trace or code (if you are OK with that), so we could help you more?

**Comment by ledinhthi** [comment]
Thank you so much, i solved it by change latim1-> utf8 :))

**Comment by PantelisGeorgiadis** [comment]
Good to hear that!

**Comment by ledinhthi** [comment]
yeahhh, i’m planning send pdf, image to pacs server now
