### ISSUE TITLE
How does the SCP service listen to client requests

### ISSUE THREAD

**Issue by CloudWoR** [PantelisGeorgiadis/dcmjs-dimse#29]
# I'm going to create a worklist server application and use this library to simulate the worklist request of the client
## this my worklist server code and client code
* SCP server:
```tsx
@Injectable()
export class WorklistServerService extends Server {
  constructor() {
    super(WorklistScpService);
    this.listen(2000, { associationTimeout: 1500 });
  }
}
```
* Client:
```tsx   const client = new Client();
    const request = new CEchoRequest();
    request.on('connect', (response: responses.CEchoResponse) => {
      console.log('response')
      if (response.getStatus() === Status.Success) {
        console.log('ECho Success!');
      }
    });
    client.addRequest(request);
    client.on('networkErrors', (e) => {
      console.log('networkErrors: ', e);
    });
    client.send('127.0.0.1', 2000, 'SCU', 'CLIENT');
```
## **I don't know where the server listens to the client's request to execute server. close()**

Reading the source code of the Server and Scp classes, I didn't find how to monitor the network connection between the client and the server

**Comment by PantelisGeorgiadis** [comment]
Hello @CloudWoR! Starting/stopping the server is rather a user-triggered process and not something that is supposed to happen within the communication workflow. Most of the implementations I've crossed, are starting the server when the service starts and ends it, when the service exits. Others are providing a UI element to the users, so they can start/stop the service manually. Hope I covered your question.

**Comment by CloudWoR** [comment]
> 你好@CloudWoR！启动/停止服务器是一个用户触发的过程，而不是在通信工作流中应该发生的事情。我遇到的大多数实现都是在服务启动时启动服务器，在服务退出时启动服务器。其他人则向用户提供 UI 元素，以便他们可以手动启动/停止服务。希望我涵盖了你的问题。



> Hello @CloudWoR! Starting/stopping the server is rather a user-triggered process and not something that is supposed to happen within the communication workflow. Most of the implementations I've crossed, are starting the server when the service starts and ends it, when the service exits. Others are providing a UI element to the users, so they can start/stop the service manually. Hope I covered your question.

Thank you. I think I should know how to handle it, but I still don't understand the following code：
```tsx
server.on('networkError', (e) => {
  console.log('Network error: ', e);
});
```
## class of Server undefined method: on(), Where did on * () come from？

**Comment by PantelisGeorgiadis** [comment]
The `Server` class, as well as several other classes in the library, extend node's `EventEmitter` (actually an asynchronous version of it). Using an event emitter, events can be raised from parts of the code and caught in `on` handlers. Check [this](https://nodejs.org/api/events.html#class-eventemitter) for more.

**Comment by CloudWoR** [comment]
thank you,Where can I query which events are defined

**Comment by PantelisGeorgiadis** [comment]
You can check which events each class emits (check `.emit`) and consume them in your event handlers (`.on`). However, I should probably create constants of these events, so users could be able to find them in one place.

**Comment by CloudWoR** [comment]
thank you for your work
