### ISSUE TITLE
Getting Called/Calling AET in handlers

### ISSUE THREAD

**Issue by hewittwill** [PantelisGeorgiadis/dcmjs-dimse#3]
Is there a straightforward way to get the Called / Calling AET from within `cStoreRequest` , `cMoveRequest` or similar ? 

There does not appear to be, and this is potentially useful. Would suggest it exists on the request object.

**Comment by hewittwill** [comment]
If there isn't a way, am happy to make a PR

**Comment by PantelisGeorgiadis** [comment]
Thank you for your comment @hewittwill! There is the 'associationAccepted' event handler that you can use to get the Called/Calling AE titles (actually the whole association object), once you have established and association. Here's how you can do it:

```js
const dcmjsDimse = require('dcmjs-dimse');
const { Client } = dcmjsDimse;
const { CEchoRequest } = dcmjsDimse.requests;
const { Status } = dcmjsDimse.constants;

const client = new Client();
const request = new CEchoRequest();
request.on('response', (response) => {
  if (response.getStatus() === Status.Success) {
    console.log('Happy!');
  }
});
client.addRequest(request);
client.on('associationAccepted', (association) => {
  console.log('Association: ', association);
  console.log('Calling AET: ', association.getCallingAeTitle());
  console.log('Called AET: ', association.getCalledAeTitle());
});
client.on('networkError', (e) => {
  console.log('Network error: ', e);
});
client.send('127.0.0.1', 12345, 'SCU', 'ANY-SCP');
```

If this doesn't fit your needs, you are more than welcome to submit a PR!

**Comment by hewittwill** [comment]
Thanks @PantelisGeorgiadis - I should've been more specific, in this case I am developing an SCP, not an SCU. In any event, I managed to find a workaround:

`this.association`

In the `Server` class

**Comment by PantelisGeorgiadis** [comment]
No problem @hewittwill! Glad you find it on your own! The SCP class also exposes the socket object so you can whitelist your incoming connections based on the calling IP address.
