### ISSUE TITLE
MPPS workflow

### ISSUE THREAD

**Issue by syed-qure** [PantelisGeorgiadis/dcmjs-dimse#31]
Many thanks for your work and for the examples provided.

I don't know what call(s) is/are made wrt MPPS and how an SCP should handle them? Any help is much appreciated.

**Comment by PantelisGeorgiadis** [comment]
Hello @syed-qure,
Thank you for your comments!

Actually, the library already implements all the parts needed to create an MPPS server! Follow the SCP example (https://github.com/PantelisGeorgiadis/dcmjs-dimse/wiki/Examples#scp) and accept presentation contexts with `SopClass` equal to `ModalityPerformedProcedureStep`. Implement the `nCreateRequest` and the `nSetRequest` handlers. Modalities are going to send you datasets in the first handler, when a procedure is started, and in the second handler, when a procedure is completed/discontinued. Read the request dataset properties and match them with your data source entries (e.g. your database). Create the corresponding response dataset, out of your data source match, and pass it to the handler callbacks, respectively. There you go… you have your first MPPS server!

**Comment by syed-qure** [comment]
Thank you so much for your response. I figured out that I can listen for nCreate and nSet in my existing scp class but I was unsure what to do with the data that is passed as request in those calls. 

Unrelated question:
Do you still feel that I can't use your lib in production?

**Comment by PantelisGeorgiadis** [comment]
That's totally up to you @syed-qure!

**Comment by syed-qure** [comment]
I have no issues so far using it but you added a note in your readme.md so I was curious if that note is still relevant

**Comment by PantelisGeorgiadis** [comment]
The note is inherited from the original dcmjs library which is the basis of this effort.

**Comment by syed-qure** [comment]
Thanks much @PantelisGeorgiadis for your work and for your answers. I appreciate it a lot. I have some questions towards creating a modality worklist.

**Comment by syed-qure** [comment]
@PantelisGeorgiadis the dataset that is passed in n-set call that modality does to scp does not have any identifier to see for what patient this call was. Am I missing something?

**Comment by PantelisGeorgiadis** [comment]
Hello @syed-qure! The library doesn’t modify or filter the received datasets in any case. This means that your modality does not include any relevant information, although it seems strange to me. Usually, the AccessionNumber and/or the StudyInstanceUID should be included so you can uniquely identify the procedure/study. Have you checked all received sequence items?

**Comment by syed-qure** [comment]
This is the value of `request.getDataset()`
```javascript

transferSyntaxUid: '1.2.840.10008.1.2',
elements: {
  _vrMap: {},
  SpecificCharacterSet: 'ISO_IR 192',
  PerformedProcedureStepEndDate: '20221221',
  PerformedProcedureStepEndTime: '153012',
  PerformedProcedureStepStatus: 'DISCONTINUED',
  PerformedSeriesSequence: []
  }
},
```

**Comment by PantelisGeorgiadis** [comment]
Strange indeed. I guess you should contact your modality's vendor to check if there's a setting missing on their side.
