### ISSUE TITLE
Creating an MWL [Modality Worklist]

### ISSUE THREAD

**Issue by syed-qure** [PantelisGeorgiadis/dcmjs-dimse#32]
What are the necessary tags that are used to create a modality work list?

**Comment by PantelisGeorgiadis** [comment]
Hi @syed-qure!
A good starting point is the "official" Modality Worklist Information Model that can be found [here](https://dicom.nema.org/medical/dicom/2014c/output/chtml/part04/sect_K.6.html). Implementing, at least, the type 1 tags, should be enough to get you going.

**Comment by syed-qure** [comment]
Does transfer syntax play any role in relaying the data to modality?

I'm sending the dataset as follows
```javascript
const dataset = new Dataset({
      Modality: 'CR',
      PatientID: '12345',
      PatientName: 'JOE^DOE',
      PatientAge: '99',
      PatientBirthDate: '20060330',
      AccessionNumber: '123321',
      ScheduledStationAETitle: 'AE_Title',
      RequestedProcedureID: 'RPID',
      ScheduledProcedureStepStartDateTime: 20060330,
    })
```
and I'm using modality emulator for simulation.

But when the emulator gets the record, it does not show ScheduledStationAETitle, RequestedProcedureID, ScheduledProcedureStepStartDateTime

And when I start MPPS Progress, it fails.

**Comment by syed-qure** [comment]
@PantelisGeorgiadis Is it absolutely necessary to send all the type 1 tags?

**Comment by PantelisGeorgiadis** [comment]
It depends on the implementation... Most of the modalities are performing validation on the received response datasets and in case a type 1 tag is missing, they reject the procedure.
Regarding the dataset you are returning to the emulator, I can see that it lacks several type 1 tags (including the Study Instance UID) plus that some of your tags (e.g. Scheduled Station AE Title, Scheduled Procedure Step Start Date Time) are supposed to be inside a Scheduled Procedure Step Sequence. Please read carefully the worklist data model and create the respecting dataset.

**Comment by syed-qure** [comment]
Agreed @PantelisGeorgiadis. I have not changed my dataset drastically and yet no luck. I have to however mention that the MPPS step passes with MinXray software.

**Comment by PantelisGeorgiadis** [comment]
Hey @syed-qure, have you managed to make your MWL server work?

**Comment by syed-qure** [comment]
Hey @PantelisGeorgiadis how should I handle the c-find request when I have no records in my database?

**Comment by syed-qure** [comment]
Hey @PantelisGeorgiadis how should I handle the c-find request when I have no records in my database?

**Comment by PantelisGeorgiadis** [comment]
Hi @syed-qure ! Just call the callback handler with an empty response (no dataset) and a success status.

**Comment by syed-qure** [comment]
Should the callback have both pending and success responses?

Also what modality emulator would you recommend for testing?

**Comment by PantelisGeorgiadis** [comment]
For an empty response, just return a success (no pending).

**Comment by syed-qure** [comment]
So for the past few weeks I've been using the modality emulator provided by DVTK for testing my MWL server. I'm able to create and send worklists to the emulator but while sending MPPS progress to the MWL server I get this error.

![Screenshot-2022-12-22-140331](https://user-images.githubusercontent.com/109221583/209092776-48712d9c-286c-4976-bb33-19c8b71ed819.png)

Is it possible for you to create a dummy MWL server and use this emulator and see if it is working for you?

**Comment by PantelisGeorgiadis** [comment]
Hi @syed-qure! Sure, I'm already familiar with this emulator. I'll try to put something together and will share the results.

**Comment by syed-qure** [comment]
Thank you so much for considering my request. I look forward for your results.

**Comment by PantelisGeorgiadis** [comment]
Hi @syed-qure! Here's an SCP class that works with the DVTk modality emulator.
```js
class MwlMppsScp extends Scp {
  constructor(socket, opts) {
    super(socket, opts);
    this.association = undefined;
  }

  // Handle incoming association requests
  associationRequested(association) {
    this.association = association;

    const contexts = association.getPresentationContexts();
    contexts.forEach((c) => {
      const context = association.getPresentationContext(c.id);
      if (
        context.getAbstractSyntaxUid() === SopClass.Verification ||
        context.getAbstractSyntaxUid() === SopClass.ModalityWorklistInformationModelFind ||
        context.getAbstractSyntaxUid() === SopClass.ModalityPerformedProcedureStep
      ) {
        const transferSyntaxes = context.getTransferSyntaxUids();
        transferSyntaxes.forEach((transferSyntax) => {
          if (
            transferSyntax === TransferSyntax.ImplicitVRLittleEndian ||
            transferSyntax === TransferSyntax.ExplicitVRLittleEndian
          ) {
            context.setResult(PresentationContextResult.Accept, transferSyntax);
          } else {
            context.setResult(PresentationContextResult.RejectTransferSyntaxesNotSupported);
          }
        });
      } else {
        context.setResult(PresentationContextResult.RejectAbstractSyntaxNotSupported);
      }
    });
    this.sendAssociationAccept();
  }

  // Handle incoming C-ECHO requests
  cEchoRequest(request, callback) {
    const response = CEchoResponse.fromRequest(request);
    response.setStatus(Status.Success);

    callback(response);
  }

  // Handle incoming C-FIND MWL requests
  cFindRequest(request, callback) {
    log.info(`C-FIND MWL Query: ${request.getDataset()}`);

    const pendingResponse = CFindResponse.fromRequest(request);
    pendingResponse.setAffectedSopClassUid(SopClass.ModalityWorklistInformationModelFind);
    pendingResponse.setDataset(
      new Dataset({
        PatientID: '12345',
        PatientName: 'JOHN^DOE',
        AccessionNumber: '76554321',
        RequestedProcedureID: '97654312',
        StudyInstanceUID: Dataset.generateDerivedUid(),
        ScheduledProcedureStepSequence: [
          {
            ScheduledStationAETitle: this.association.getCallingAeTitle(),
            ScheduledStationName: '',
            ScheduledProcedureStepStartDate: '20221226',
            ScheduledProcedureStepStartTime: '000000',
            Modality: 'CT',
          },
        ],
      })
    );
    pendingResponse.setStatus(Status.Pending);

    const finalResponse = CFindResponse.fromRequest(request);
    pendingResponse.setAffectedSopClassUid(SopClass.ModalityWorklistInformationModelFind);
    finalResponse.setStatus(Status.Success);

    callback([pendingResponse, finalResponse]);
  }

  // Handle incoming N-CREATE MPPS requests
  nCreateRequest(request, callback) {
    log.info(`N-CREATE MPPS Query: ${request.getDataset()}`);

    const response = NCreateResponse.fromRequest(request);
    response.setStatus(Status.Success);
    callback(response);
  }

  // Handle incoming N-SET MPPS requests
  nSetRequest(request, callback) {
    log.info(`N-SET MPPS Query: ${request.getDataset()}`);

    const response = NSetResponse.fromRequest(request);
    response.setStatus(Status.Success);
    callback(response);
  }

  // Handle incoming association release requests
  associationReleaseRequested() {
    this.sendAssociationReleaseResponse();
  }
}
```
I think that your issue was that you weren't setting the correct affected SOP class for your responses since the default constructor assumes that you are responding to a `StudyRootQueryRetrieveInformationModelFind` SOP class.

**Comment by syed-qure** [comment]
@PantelisGeorgiadis Thanks so much for your response. I shall try this and let you know.

**Comment by syed-qure** [comment]
@PantelisGeorgiadis inside `cFindRequested` method, after you've initialised `finalResponse` you've again set `pendingResponse.setAffectedSopClassUid`. Is that supposed to be `finalResponse.setAffectedSopClassUid`?

**Comment by syed-qure** [comment]
@PantelisGeorgiadis I tried your example and I cannot tell you how much I appreciate what you're doing. It worked amazingly. Thank you so very much.

**Comment by PantelisGeorgiadis** [comment]
> @PantelisGeorgiadis inside `cFindRequest` method, after you've initialised `finalResponse` you've again set `pendingResponse.setAffectedSopClassUid`. Is that supposed to be `finalResponse.setAffectedSopClassUid`?
> 
> ```js
> cFindRequest(request, callback) {
>   
>     ...
> 
>     const finalResponse = CFindResponse.fromRequest(request);
>     // should this be finalResponse?
>     pendingResponse.setAffectedSopClassUid(SopClass.ModalityWorklistInformationModelFind);
>     finalResponse.setStatus(Status.Success);
> 
>     callback([pendingResponse, finalResponse]);
>   }
> ```

Of course it is `finalResponse` instead of `pendingResponse`! Thanks for noticing this and for your kind comments!

**Comment by syed-qure** [comment]
Hey @PantelisGeorgiadis you've done a lot to help me out and I'm very grateful for it. I'm coming to you with the last piece that I have to solve. As I have mentioned previously about how my N-SET response does not really have any identifier linked to patient, can you please see if in your example you are getting anything like a PatientID or something else?

**Comment by PantelisGeorgiadis** [comment]
N-CREATE MPPS Query: Dataset:
```json
{
  "_vrMap": {},
  "00080000": [
    {}
  ],
  "SpecificCharacterSet": "ISO_IR 192",
  "Modality": "CT",
  "ProcedureCodeSequence": [],
  "ReferencedPatientSequence": [],
  "00100000": [
    {}
  ],
  "PatientName": "JOHN^DOE",
  "PatientID": "12345",
  "IssuerOfPatientID": "Issuer of Patient ID1",
  "PatientBirthDate": "",
  "PatientSex": "",
  "00180000": [
    {}
  ],
  "ImageAndFluoroscopyAreaDoseProduct": null,
  "00200000": [
    {}
  ],
  "StudyID": "Procedure ID1",
  "00400000": [
    {}
  ],
  "PerformedStationAETitle": "DVT",
  "PerformedStationName": "",
  "PerformedLocation": "",
  "PerformedProcedureStepStartDate": "20230103",
  "PerformedProcedureStepStartTime": "105550",
  "PerformedProcedureStepEndDate": "",
  "PerformedProcedureStepEndTime": "",
  "PerformedProcedureStepStatus": "IN PROGRESS",
  "PerformedProcedureStepID": "1605.0",
  "PerformedProcedureStepDescription": "",
  "PerformedProcedureTypeDescription": "",
  "PerformedProtocolCodeSequence": [],
  "ScheduledStepAttributesSequence": [
    {
      "_vrMap": {},
      "00080000": [
        {}
      ],
      "AccessionNumber": "76554321",
      "ReferencedStudySequence": [
        {
          "_vrMap": {},
          "00080000": [
            {}
          ],
          "ReferencedSOPClassUID": "1.2.840.10008.3.1.2.3.1",
          "ReferencedSOPInstanceUID": "1.2.840.10008.5.1.4.1.1.9.1.2.1.1.1"
        }
      ],
      "00200000": [
        {}
      ],
      "StudyInstanceUID": "2.25.340911595870306943493101722618826997131",
      "00320000": [
        {}
      ],
      "RequestedProcedureDescription": "",
      "00400000": [
        {}
      ],
      "ScheduledProcedureStepDescription": "",
      "ScheduledProtocolCodeSequence": [],
      "ScheduledProcedureStepID": "",
      "RequestedProcedureID": "97654312"
    }
  ],
  "PerformedProcedureStepDiscontinuationReasonCodeSequence": [],
  "TotalNumberOfExposures": 0,
  "ExposureDoseSequence": [],
  "CommentsOnRadiationDose": "",
  "FilmConsumptionSequence": [],
  "PerformedSeriesSequence": []
}
```

N-SET MPPS Query: Dataset:
```json
{
  "_vrMap": {},
  "00080000": [
    {}
  ],
  "ProcedureCodeSequence": [],
  "00180000": [
    {}
  ],
  "ImageAndFluoroscopyAreaDoseProduct": 0.5703,
  "00400000": [
    {}
  ],
  "PerformedProcedureStepEndDate": "20230103",
  "PerformedProcedureStepEndTime": "105600",
  "PerformedProcedureStepStatus": "DISCONTINUED",
  "PerformedProcedureStepDescription": "",
  "PerformedProcedureTypeDescription": "",
  "PerformedProtocolCodeSequence": [],
  "PerformedProcedureStepDiscontinuationReasonCodeSequence": [],
  "TotalNumberOfExposures": 2,
  "ExposureDoseSequence": [
    {
      "_vrMap": {},
      "00180000": [
        {}
      ],
      "KVP": 48,
      "ExposureTime": 23,
      "RadiationMode": "PULSED",
      "XRayTubeCurrentInuA": 259085
    },
    {
      "_vrMap": {},
      "00180000": [
        {}
      ],
      "KVP": 46,
      "ExposureTime": 16,
      "RadiationMode": "PULSED",
      "XRayTubeCurrentInuA": 242655
    }
  ],
  "CommentsOnRadiationDose": "1, Hand pa, 48kV, 5.946mAs, 22.95ms, SID 1100, EI 80, 0mmAl, 0.3575dGycm2, ,\r\n2, Hand lat, 46kV, 3.948mAs, 16.27ms, SID 1100, EI 160, 0mmAl, 0.2128dGycm2, ,",
  "FilmConsumptionSequence": [],
  "PerformedSeriesSequence": [
    {
      "_vrMap": {},
      "00080000": [
        {}
      ],
      "RetrieveAETitle": "",
      "SeriesDescription": "",
      "PerformingPhysicianName": "",
      "OperatorsName": "DVT Service",
      "ReferencedImageSequence": [],
      "00180000": [
        {}
      ],
      "ProtocolName": "DEMO_Hand",
      "00200000": [
        {}
      ],
      "SeriesInstanceUID": "1.2.826.0.1.3680043.2.1545.1.2.1.7.20230103.105550.586.14",
      "00400000": [
        {}
      ],
      "ReferencedNonImageCompositeSOPInstanceSequence": []
    }
  ]
}
```

These are the value that the emulator returns, by using the default settings. However, the returned tags are configurable in by editing the `MPPS-Progress`, `MPPS-Completed` and `MPPS-Discontinued` tabs.
<br>
If the N-SET dataset tags won't help you identify the procedure, you can rely on the `affectedSopInstanceUid` value. When receiving an N-CREATE request, you should check the command's `affectedSopInstanceUid` property. If this is empty you should generate a UID and set it as the response's affectedSopInstanceUid value. If there an already proposed UID, use that in the response's `affectedSopInstanceUid`. In both cases, associate that UID with the procedure, in your database. When the modality is going to send you an N-SET request referring to that particular procedure, it is going to use that UID in the command's `affectedSopInstanceUid`.

**Comment by syed-qure** [comment]
Thank you for your response. I'll check this.

**Comment by CloudWoR** [comment]
When implementing the above code, I found a problem: **How to return multiple worklist queues?**
Usually, when a device requests an MWL server, it will return a worklist queue containing multiple check information. I have found that in the `cFindRequest()` method, a set of **cFindRequest** type data can be returned through a callback, for example:
 ` callback ([pendingResponse, pendingResponse, finalResponse]); `
Can return two identical Dataset data.
May I ask how to achieve the following requirements

**Comment by CloudWoR** [comment]
I think I have solved this problem:
The object returned by the CFindResponse. formRequest (request) method exists independently, so the pendingResponse implementation can be created multiple times through this method:
```ts
packageDataset(
    request: requests.CFindRequest,
    examinations: V_Examinations[],
    mwlScpOptions: TMWL_SCP_OPTIONS,
    callingAeTitle: string,
  ) {
    const pendingResponses: responses.CFindResponse[] = [];
    for (let i = 0; i < examinations.length; i++) {
      const pendingResponse = responses.CFindResponse.fromRequest(request);
      pendingResponse.setAffectedSopClassUid(
        SopClass.ModalityWorklistInformationModelFind,
      );
      const elements = PackageDataset.createElements(
        examinations[i],
        mwlScpOptions,
        callingAeTitle,
      );
      pendingResponse.setDataset(new Dataset(elements));
      pendingResponse.setStatus(Status.Pending);
      pendingResponses.push(pendingResponse);
    }
    return pendingResponses;
  }
```

**Comment by PantelisGeorgiadis** [comment]
Glad you figured it out @CloudWoR! Just don't forget to add to your array of responses a final one with success status.
