### ISSUE TITLE
Extracting image overlay

### ISSUE THREAD

**Issue by DeanKezurer** [PantelisGeorgiadis/dcmjs-dimse#33]
Hi all,
I am currently working with DICOM images and want to isolate the images from any external information on it. I am aware of the BurnedInAnnotation tag, and I believe that this is associated with some sort of image overlay being appended to the image. My end goal is to extract the overlay information as an object.
Has anyone had any experience with this type of task? Any help would be greatly appreciated.
Thanks,
Dean

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! Thank you for your question! Are you receiving datasets containing the `BurnedInAnnotation` tag using an `SCP`? If that's the case, once you have received your dataset inside the `cStoreRequest` handler, you can access all tags (including the `BurnedInAnnotation`) using the 'getElement' accessor (e.g. `dataset.getElement('BurnedInAnnotation')`). Hope I helped!

**Comment by DeanKezurer** [comment]
Hi @PantelisGeorgiadis. Thank you for the speedy response! I was able to successfully obtain the value of that tag, but I was wondering if there was a way to extract the actual information that was burned into the existing picture. From my understanding the BurnedInAnnotation tag is simply an indicator of whether or not there is additional information within the DICOM image. Once again, thank you for your help!

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! You are right, `BurnedInAnnotation` is a YES/NO flag that "indicates whether or not image contains sufficient burned in annotation to identify the patient and date the image was acquired". However, I don't think that `dcmjs-dimse` would help you extract that information from the image pixels.

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! Did you manage to extract the information you needed from the image pixels?

**Comment by PantelisGeorgiadis** [comment]
@DeanKezurer, I'm closing this issue now. If you still have issues extracting the information you need from your datasets, please open a new issue.
