### ISSUE TITLE
Greater control of presentation contexts on C-GET

### ISSUE THREAD

**Issue by richard-viney** [PantelisGeorgiadis/dcmjs-dimse#34]
We have a situation where I believe greater control over the presentation contexts for an association is needed, which doesn't seem to currently be possible as a lot of PCs get added by default.

The situation is this: we are doing a C-GET of a single DICOM and we know the `SOPClassUID` of the DICOM we're retrieving, but we don't know the transfer syntax. In this case we want to give the SCP the best opportunity to send us the DICOM in its native transfer syntax, i.e. no transcoding or decompression. A way to achieve this is to add one PC per transfer syntax that we support, i.e.

```
PC #1: <SOPClassUID> + JPEGBaselineProcess1
PC #3: <SOPClassUID> + JPEGBaselineProcess2And4
PC #5: <SOPClassUID> + JPEGLosslessProcess14
PC #7: <SOPClassUID> + JPEGLosslessProcess14V1
PC #9: <SOPClassUID> + JPEGLSLossless
PC #11: <SOPClassUID> + JPEGLSLossy
PC #13: <SOPClassUID> + JPEG2000LosslessOnly
PC #15: <SOPClassUID> + JPEG2000Lossy
PC #17: <SOPClassUID> + DeflatedExplicitVRLittleEndian
PC #19: <SOPClassUID> + RLELossless
PC #21: <SOPClassUID> + ImplicitVRLittleEndian
PC #23: <SOPClassUID> + ExplicitVRLittleEndian
PC #25: <SOPClassUID> + ExplicitVRBigEndian
```

This gives the SCP the opportunity to select the PC that matches a DICOM's native transfer syntax when doing a C-GET. This approach is described here: https://pydicom.github.io/pynetdicom/dev/user/presentation.html

Is this currently possible in dcmjs-dimse? Or do we need to add a way to skip/bypass the current default presentation contexts that are added automatically so that the user can specify the exact ones that they want?

**Comment by PantelisGeorgiadis** [comment]
Hi Richard!
I understand the scenario that you are describing. Unfortunately, this is currently not possible since, for C-GET operations, dcmjs-dimse always adds all known (to the library) storage SOP class UIDs to the association. This was done, mainly, to make the life of the caller easier. However, I think that we need to introduce a property in the `CGetRequest` class that would override that behavior (default is enabled so we won’t break current functionality). In this way, the user would have the chance to introduce custom presentation contexts, by calling `Client`’s `addAdditionalPresentationContext` function.

Thoughts?

**Comment by richard-viney** [comment]
Yes I think what you describe would be quite reasonable, i.e. a way to disable the current behaviour so that the user of the library can set their own PCs.

A related change is also needed: allowing PCs that have the same Abstract Syntax UID. Currently functions such as `addOrGetPresentationContext()` look like they may prevent configuring PCs as described above, i.e. multiple ones which have the same Abstract Syntax UID but specify a different transfer syntax(es).

Is there anything else you think can see would be needed?

**Comment by PantelisGeorgiadis** [comment]
Hi Richard!
Version 0.1.15 was just released, and it includes the necessary updates that can enable greater control of presentation contexts for C-GET requests. More specifically, the `getAddStorageSopClassesToAssociation`/`setAddStorageSopClassesToAssociation` functions were introduced to `CGetRequest`, that enables the addition of all known storage SOP classes, as presentation contexts, during an association (default is true). Additionally, the `addAdditionalPresentationContext` function now accepts an optional parameter to “force” the addition of the provided context, as a new one, irrespectively if the respected SOP class already exists in the association.
I used the following example to create the kind of C-GET request you described.
```js
const client = new Client();
  
const request = CGetRequest.createStudyGetRequest(studyInstanceUid);
request.setAddStorageSopClassesToAssociation(false);
client.addRequest(request);

client.addAdditionalPresentationContext(
  new PresentationContext(0, StorageClass.MrImageStorage, TransferSyntax.Jpeg2000Lossless)
);
client.addAdditionalPresentationContext(
  new PresentationContext(0, StorageClass.MrImageStorage, TransferSyntax.JpegLsLossless),
  true
);
client.addAdditionalPresentationContext(
  new PresentationContext(0, StorageClass.MrImageStorage, TransferSyntax.ImplicitVRLittleEndian),
  true
);

client.on('cStoreRequest', (request, callback) => {
  const response = CStoreResponse.fromRequest(request);
  response.setStatus(Status.Success);
  callback(response);
});
client.send('127.0.0.1', 12345, 'SCU', 'ANY-SCP');
```
Please test and let me know of your results!

**Comment by richard-viney** [comment]
Amazing, thank you! We will try this out and let you know how we get on. @ericlin-nz

**Comment by ericlin-nz** [comment]
Hi @PantelisGeorgiadis, thank you for the version update! I've given this a test and it is working well!
