### ISSUE TITLE
Sending cEcho from browser to SCP

### ISSUE THREAD

**Issue by syed-qure** [PantelisGeorgiadis/dcmjs-dimse#37]
I followed [this](https://github.com/PantelisGeorgiadis/dcmjs-dimse#c-echo-scu) example of sending a cEcho request from browser to a locally running scp server and I'm getting the following error.

Any help is much appreciated

<img width="900" alt="Screenshot 2023-01-19 at 12 36 19 PM" src="https://user-images.githubusercontent.com/109221583/213377371-ae54408e-895d-42ea-a095-edb656ff2eb8.png">

**Comment by PantelisGeorgiadis** [comment]
Hello @syed-qure! As far as I know, there's no TCP socket implementation for the browser. This is only available in Node.js. I think that what you are trying to achieve, is not currently possible, at least not directly.

**Comment by syed-qure** [comment]
Can you suggest how I can achieve this?

**Comment by PantelisGeorgiadis** [comment]
Hi @syed-qure! There are options but the majority (if not all) of them require a back-end that would act as a proxy to your socket communication. Check [this](https://stackoverflow.com/questions/63626831/call-normal-socket-from-a-web-browser).

**Comment by syed-qure** [comment]
Thank you @PantelisGeorgiadis
