### ISSUE TITLE
Saving with Meta

### ISSUE THREAD

**Issue by hewittwill** [PantelisGeorgiadis/dcmjs-dimse#4]
Hi there

We're trying to save the output of `cStoreRequest` to a file, and it does not appear to contain the meta tags and the preamble. 

We've tried creating a `DicomMeta` and writing that first from, from the dcm-js library, but that does not appear to work. 

Is there a preferred way to write a valid DICOM file from cStoreRequest?

**Comment by hewittwill** [comment]
Note: found a solution, but leaving the issue open as either a) should consider creating a helper function for this in the `Dataset` class or b) there may be an existing, preferred way to achieve this that I wasn't aware of.

```
      const tempDs = new data.DicomDict({
        "00020001": {
          vr: "OB",
          Value: Buffer.from([0, 1]),
        },
        "00020002": {
          vr: "UI",
          Value: ds.getElement("SOPClassUID"),
        },
        "00020003": {
          vr: "UI",
          Value: ds.getElement("SOPInstanceUID"),
        },
        "00020010": {
          vr: "UI",
          // TODO: this shouldnt be hardcoded
          Value: "1.2.840.10008.1.2",
        },
      });

...
      // write the file metadata
      await fh.write(Buffer.from(tempDs.write()));

     //  write the file buffer
     await fh.write(buffer);

```

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! Thank your for your comment! Indeed, during C-STORE operations, the File Meta Information header and the preamble are not transmitted over the network. However, the information contained in the File Meta Information header can be derived from the actual dataset, as you already figured. I will consider adding a helper function in the `Dataset` class in a next version, as you suggested.

**Comment by hewittwill** [comment]
If you're happy to take PRs, I'll look to adding this enhancement

**Comment by PantelisGeorgiadis** [comment]
@hewittwill, of course I am!

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! The `Dataset` class has now a `toFile` function that saves all elements in a DICOM part10 file!

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! Are you happy with the `toFile` implementation? Is it OK to close this?

**Comment by hewittwill** [comment]
I believe writeFileSync is deprecated, or not considered best practice, we could consider using writeFile (async) ? Which the end-user can await if necessary

**Comment by PantelisGeorgiadis** [comment]
Hi @hewittwill! `writeFileSync` is not deprecated but `writeFile` without providing a callback is. In any case, both `fromFile` and to `toFile` are now accepting a callback that can be used to run the functions asynchronously. In case the callback function is not provided, the functions run synchronously (as they used to).

**Comment by PantelisGeorgiadis** [comment]
Hi @hewittwill! Are you happy with the async/sync implementations of Dataset read/write to/from part10 files? Should we close this one?

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! Closing the issue now. If you feel that we can do more on that, please reopen or create a new issue.
