### ISSUE TITLE
US cineloops with Transfer Syntax RLE Lossless are broken when received or sent with dcmjs-dimse

### ISSUE THREAD

**Issue by jimOnAir** [PantelisGeorgiadis/dcmjs-dimse#40]
Hello. 
I've found that some US cineloops are broken when received or sent with dcmjs-dimse. 
Looking into this issue I've found that dcmjs splits PixelData in `1024 * 20` bytes fragments by default in DicomMessage.write() which is causes the issue. This behaviour can be overwritten while saving dataset to local drive with passing `{ fragmentMultiframe: false }` value to writeOptions argument of `Dataset.toFile()`, but there is no such option for  `Dataset.getDenaturalizedCommandDataset()` which is used to C-STORE requests over network. And seems like there is a lot of places where this option must be passed if I need change this behaviour.
Code that I've used for testing:
```js
class DicomPatcher {
    static async patchFile(filePath) {
      const dicomPatcher = new DicomPatcher();

      await dicomPatcher.patchFile(filePath);
    }

    async patchFile(filePath) {
      const dicomDataset = await this.dataSetFromFile(filePath);
      await this.dataSetToFile(dicomDataset, filePath + '-patched.dcm');
    }

    async dataSetFromFile(filePath) {
      return new Promise((resolve, reject) => {
        Dataset.fromFile(filePath, (error, result) => {
          if (error) {
            return reject(error);
          }

          resolve(result);
        });
      });
    }

    async dataSetToFile(dataSet, filePath) {
      return new Promise((resolve, reject) => {
        dataSet.toFile(filePath, (error) => {
          if (error) {
            return reject(error);
          }

          resolve();
        }, undefined,
        //  { fragmentMultiframe: false }
         );
      });
    }

  }

  (async () => {
    DicomPatcher.patchFile('/Users/dmitry/Downloads/test.dcm');
  })();

```

The actual error I get with futher processing of the file with dcm2jpg from dcm4che toolkit:
```console
$ find . -name '*.dcm' -exec /opt/dcm4che/bin/dcm2jpg {} {}.jpg \;
./1.2.156.112536.1.2118.80201085056.14485206710.12.dcm-patched.dcm -> ./1.2.156.112536.1.2118.80201085056.14485206710.12.dcm-patched.dcm.jpg
Native OpenCV library has been found in /opt/dcm4che/lib/macosx-aarch64/libopencv_java.dylib
08:49:55.929 DEBUG - Decompressor: org.dcm4che3.imageio.plugins.rle.RLEImageReader
08:49:55.930 DEBUG - Start decompressing frame #1
08:49:55.933 INFO  - RLE Segment #1 too short, set missing 363917 bytes to 0
08:49:55.933 INFO  - RLE Segment #2 too short, set missing 480000 bytes to 0
08:49:55.933 INFO  - RLE Segment #3 too short, set missing 480000 bytes to 0
08:49:55.933 DEBUG - Finished decompressing frame #1
```
and with  dcmj2pnm from dcmtk

```console
$ dcmj2pnm --nointerlace --write-png --accept-acr-nema --frame 1 1.2.156.112536.1.2118.80201085056.14485206710.12.dcm-patched.dcm 1.2.156.112536.1.2118.80201085056.14485206710.12.dcm-patched.png --debug
D: $dcmtk: dcmj2pnm v3.6.7 2022-04-22 $
D:
D: DcmDataDictionary: Loading file: /usr/share/dcmtk/dicom.dic
I: reading DICOM file: 1.2.156.112536.1.2118.80201085056.14485206710.12.dcm-patched.dcm
D: DcmMetaInfo::checkAndReadPreamble() TransferSyntax="Little Endian Explicit"
D: DcmDataset::read() TransferSyntax="RLE Lossless"
I: preparing pixel data
D: transfer syntax of DICOM dataset: RLE Lossless (1.2.840.10008.1.2.5)
D: using partial read access to compressed pixel data
D: RLE decoder processes frame 0
D: RLE decoder processes pixel item 1
Segmentation fault
```

So my questions are:

- What is the purpose of this splitting?
- Could it be turned off by default in dcmjs-dimse?
- What is the best way to configure it for C-STORE request if it couldn't be turned off?

**Comment by PantelisGeorgiadis** [comment]
Hello @jimOnAir! 
Thank you for reporting this and for your detailed analysis. I really don’t know the logic behind splitting multiframes into 1024 * 20 bytes fragments, adopted by dcmjs. However, I noticed that you added a respecting issue in dcmjs’s repo and I’m pretty sure that you’ll get the explanation soon.

However, your observation is perfectly valid! Currently, there’s no way to pass write options to `Dataset.getDenaturalizedDataset()` (not `Dataset.getDenaturalizedCommandDataset()`) and this needs to change. Same write options need to be able to be passed in the `Network`, `Server` and `Client` classes (e.g. `opts.datasetWriteOptions`).

Will change that ASAP.

**Comment by PantelisGeorgiadis** [comment]
@jimOnAir, latest release (v0.1.17) introduces the `datasetWriteOptions` option in the `Client` and `Network` class that allows the caller to pass any arguments to the `getDenaturalizedDataset` function and, hence, to dcmjs's `DicomMessage.write` method.

**Comment by jimOnAir** [comment]
That was incredebly fast. Thank you very much!
