### ISSUE TITLE
Support for AGFA NX

### ISSUE THREAD

**Issue by benjiJanssens** [PantelisGeorgiadis/dcmjs-dimse#43]
Hi all!

I've been implementing this library for building a modality worklist and successfully got it working with both the DVTk Modality Emulator and DCMTK, but I just got my hands on an AGFA NX machine, which I don't seem to get working as easily.

At first, I had some issues that I resolved by adding fields to the dataset and now I got to a point where it works in the configurator, but I'm still encountering some issues in NX itself. As soon as I press "Search RIS" it keeps loading until it times out with the following errors in NX:
<img width="493" alt="Scherm­afbeelding 2023-03-27 om 17 12 59" src="https://user-images.githubusercontent.com/24613245/227983731-da5b1bfe-c302-456b-804b-26e647c23308.png">

In the logs of my DICOM service I can see the following:
`2023-03-27T15:20:08.474Z -- INFO -- NX_VAM2048 -> Abort (A-ABORT) [source: Service user, reason: Not specified]`
`2023-03-27T15:20:08.474Z -- ERROR -- NX_VAM2048 -> Exceeded PDU timeout (60000), closing connection...`
`2023-03-27T15:20:08.476Z -- INFO -- NX_VAM2048 -> Connection closed`

I hope someone can help me out... Thanks in advance!

EDIT: I can see the following logs in my DICOM service after querying the RIS in the configurator, so although it works, perhaps it doesn't work correctly either?
`2023-03-27T15:23:56.777Z -- ERROR -- cCancelRequest method must be implemented`
`2023-03-27T15:23:57.218Z -- ERROR -- NX_VAM2048 -> Connection error: read ECONNRESET`
`2023-03-27T15:23:57.218Z -- INFO -- NX_VAM2048 -> Connection closed`
`2023-03-27T15:24:10.608Z -- INFO -- NX_VAM2048 -> Abort (A-ABORT) [source: Service user, reason: Not specified]`
`2023-03-27T15:24:10.609Z -- ERROR -- NX_VAM2048 -> Exceeded PDU timeout (60000), closing connection...`
`2023-03-27T15:24:10.610Z -- INFO -- NX_VAM2048 -> Connection closed`

**Comment by PantelisGeorgiadis** [comment]
Hello @benjiJanssens! 
I'm super-excited to hear that you have created a modality worklist using `dcmjs-dimse`! 

Although, you could implement an empty `cCancelRequest` event handler (C-CANCEL doesn't expect a response) in your `Scp`-derived class to get rid of the error, I'm not convinced that this will solve your issue.

When you press the "Search RIS" button, is your `cFindRequest` event handler getting hit or things have already gone wrong at the association stage?

**Comment by benjiJanssens** [comment]
Hi @PantelisGeorgiadis, thanks for the help!

By implementing an empty `cCancelRequest` event handler, the error has indeed disappeared, but the issue does remain.

The `cFindRequest` event handler does get triggered as I can see a response going out (and even coming in in the configurator), so it's definitely not an issue during association...

**Comment by benjiJanssens** [comment]
I seem to have fixed it by simply adding a final response, as shown in the SCP example! 🎉 
It wasn't necessary in the other emulators, so I omitted it before, but it seems required in AGFA NX...

Thank you a lot for this library and all of your help though! Much appreciated!

**Comment by PantelisGeorgiadis** [comment]
Hello @benjiJanssens! Glad that you solved your issue!
Yes, a final response is mandatory and I wonder how the emulators worked! I bet that they presented the results but, internally, they logged some kind of error.

**Comment by benjiJanssens** [comment]
@PantelisGeorgiadis yeah, that was my thought as well: just like the configurator, they probably already showed the results, but were still awaiting a final response and eventually timing out in the background.
