### ISSUE TITLE
C_Store bug

### ISSUE THREAD

**Issue by CloudWoR** [PantelisGeorgiadis/dcmjs-dimse#45]
I have found a problem that when using Store to transfer a large number of dcm files to a PACS server, it will cause other SCU clients within the local area network to be unable to perform Echo testing on the PACS server. Is this the reason why the SCU client I created myself did not fully comply with the DICOM protocol during the process of transferring dcm files?

**Comment by PantelisGeorgiadis** [comment]
Thank you @CloudWoR for reporting this!

The C-STORE operation that you are performing (regardless of its length) should not block other clients from performing other operations. However, I believe that it has nothing to do with dcmjs-dimse and it is related to your PACS design, or its configuration. I have seen systems that, due to licensing or other configuration issues, accept only one association at time. Could you please check and make sure that this is not the case? How about if you use two other clients other than dcmjs-dimse?

The command datasets that the library is sending have been validated against DVTk and found to be compatible with the protocol. However, I’m not sure about the contents of the datasets that you are transferring. In any case, this shouldn’t block other clients and, in case of any incompatibility, the PACS should respond with an error status.

**Comment by CloudWoR** [comment]
Sorry, I didn't clarify the issue. The PACS server is in production mode, and I now need to use the dcmjs dimse library to send CT data for 600 patients. Each patient has approximately 900 DCM files. I wrote a client to send according to the method in README, traversing the entire folder and sending each DCM file separately. When sending to PACS, the connection between another client in the local area network and PACS timed out. It is clear that PACS does not impose restrictions on client sending.

**Comment by CloudWoR** [comment]
`
import { SendMessageService } from '@libs/send-message';
import { Injectable } from '@nestjs/common';
import { E_EchoStatus, EchoResult } from '@preload/DimseLibDto/DimseClient.dto';
import { T_Dicom } from '@preload/entities/dicom.entity';
import { MessageType } from '@preload/ipcRender.dto';
import { Client, requests, constants, responses } from 'dcmjs-dimse';

@Injectable()
export class DimseClientService {
  private ZmClient = new Client();
  private Status = constants.Status;
  constructor(
    private readonly sendMessage: SendMessageService,
  ) {}

  public Echo(options: T_Dicom): Promise<EchoResult> {
    const { CEchoRequest } = requests;
    const request = new CEchoRequest();
    return new Promise((resolve) => {
      request.on('response', (response: responses.CEchoResponse) => {
        if (response.getStatus() === this.Status.Success) {
          resolve({
            status: E_EchoStatus.Success,
            message: `${options.scpName} 测试成功！`,
          });
        }
      });
      this.ZmClient.addRequest(request);
      this.ZmClient.on('networkError', (e: Error) => {
        resolve({
          status: E_EchoStatus.NetworkError,
          message: e.message,
        });
      });
      this.clientSend(options);
    })
  }

  public Store(dcmFile: string, scp: T_Dicom) {
    const { CStoreRequest } = requests;
    const request = new CStoreRequest(dcmFile);
    this.ZmClient.addRequest(request);
    this.ZmClient.on('netWorkError', (e) => {
      this.sendMessage.send(MessageType.Error, e);
    });
    request.on('response', (response: responses.CStoreResponse) => {
      if (response.getStatus() !== this.Status.Success) {
        this.sendMessage.send(MessageType.Error, '传送失败');
      }
    });
    request.removeAllListeners();
    this.ZmClient.removeAllListeners();
    this.clientSend(scp);
  }

  private clientSend(scp: T_Dicom) {
    const { ipAddress, port, localAeTitle, aeTitle } = scp;
    this.ZmClient.send(ipAddress, port, localAeTitle, aeTitle);
  }
}
`

**Comment by CloudWoR** [comment]
this is my clinet class
```tsc
import { SendMessageService } from '@libs/send-message';
import { Injectable } from '@nestjs/common';
import { E_EchoStatus, EchoResult } from '@preload/DimseLibDto/DimseClient.dto';
import { T_Dicom } from '@preload/entities/dicom.entity';
import { MessageType } from '@preload/ipcRender.dto';
import { Client, requests, constants, responses } from 'dcmjs-dimse';

@Injectable()
export class DimseClientService {
  private ZmClient = new Client();
  private Status = constants.Status;
  constructor(
    private readonly sendMessage: SendMessageService,
  ) {}

  public Echo(options: T_Dicom): Promise<EchoResult> {
    const { CEchoRequest } = requests;
    const request = new CEchoRequest();
    return new Promise((resolve) => {
      request.on('response', (response: responses.CEchoResponse) => {
        if (response.getStatus() === this.Status.Success) {
          resolve({
            status: E_EchoStatus.Success,
            message: `${options.scpName} 测试成功！`,
          });
        }
      });
      this.ZmClient.addRequest(request);
      this.ZmClient.on('networkError', (e: Error) => {
        resolve({
          status: E_EchoStatus.NetworkError,
          message: e.message,
        });
      });
      this.clientSend(options);
    })
  }

  public Store(dcmFile: string, scp: T_Dicom) {
    const { CStoreRequest } = requests;
    const request = new CStoreRequest(dcmFile);
    this.ZmClient.addRequest(request);
    this.ZmClient.on('netWorkError', (e) => {
      this.sendMessage.send(MessageType.Error, e);
    });
    request.on('response', (response: responses.CStoreResponse) => {
      if (response.getStatus() !== this.Status.Success) {
        this.sendMessage.send(MessageType.Error, '传送失败');
      }
    });
    request.removeAllListeners();
    this.ZmClient.removeAllListeners();
    this.clientSend(scp);
  }

  private clientSend(scp: T_Dicom) {
    const { ipAddress, port, localAeTitle, aeTitle } = scp;
    this.ZmClient.send(ipAddress, port, localAeTitle, aeTitle);
  }
}
`

**Comment by PantelisGeorgiadis** [comment]
Hi @CloudWoR!
The first thing that I noticed by checking your code is that you are opening one connection and one association per request/file. This could significantly impact the performance of the server (and the client). You can change your code so you can batch all your requests in one association. For example:
```js
const client = new Client();
const filesToPush = ScanFolderForDicomFilesToPush(folderPath);
filesToPush.forEach((fileToPush) => {
	const request = new CStoreRequest(fileToPush);
   	client.addRequest(request);
});
client.send('127.0.0.1', 12345, 'SCU', 'ANY-SCP');
```
Actually, you can add any type of request (e.g. C-ECHO, C-FIND, C-STORE, etc.) and the `Client` will figure the proper association that needs to be done. Please implement this approach and check if it solves your issue.

**Comment by PantelisGeorgiadis** [comment]
Hello @CloudWoR! Any feedback from batching your requests?

**Comment by CloudWoR** [comment]
Sorry for not responding in a timely manner. Thank you for your guidance. The code is working very well. If there are any problems in practice, I will provide you with timely feedback！

**Comment by PantelisGeorgiadis** [comment]
Glad to hear that @CloudWoR!
