### ISSUE TITLE
Pass SNICallback through to TLS options

### ISSUE THREAD

**Issue by richard-viney** [PantelisGeorgiadis/dcmjs-dimse#46]
Hi Pantelis,

Could we add `SNICallback` to the list of allowed security options, or maybe just pass everything through and use the types from @types/node on that parameter?

Thanks!

**Comment by PantelisGeorgiadis** [comment]
Hello Richard! `SNICallback` was added in `Network`, `Server` and `Client` options. Now that I'm thinking of it, I believe that this is a server feature and, therefore, this was not  necessary to be included in the `Client`, right? If that's the case, I'm going to remove it in the next release.

Please test and let me know if the type I added are OK.

**Comment by richard-viney** [comment]
Looks great, but yes it is only an option for servers I believe.

**Comment by PantelisGeorgiadis** [comment]
Thank you Richard! In the latest update, `SNICallback` was removed from the `Client` options.
