### ISSUE TITLE
LUTData (0028,3006) element in dataset breaks sending C-Store request

### ISSUE THREAD

**Issue by andreidubov** [PantelisGeorgiadis/dcmjs-dimse#47]
Hello,

Recently, I got the error like `First argument to DataView constructor must be an ArrayBuffer` when receiving or sending a `C-Store` request in `dcmjs-dimse`. After investigating, I found out that in the received dataset there is a `LUTData` (0028,3006) element, which lead to this error. The main problem locates in `dcmjs` (PR [https://github.com/dcmjs-org/dcmjs/pull/343](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2Fdcmjs-org%2Fdcmjs%2Fpull%2F343&cc_key=)). But there is a workaround for this issue: we can override `NameMap` (Additional DICOM tags to recognise when denaturalizing the dataset) when calling `DicomMetaDictionary.denaturalizeDataset()`.

`dcmjs-dimse` has the ability to pass `nameMap` to the `Dataset.toFile()` function and it works good.
But the issue is still present when sending a `C-Store` request in `Network._sendPDataTF() -> Dataset.getDenaturalizedDataset()` function.

It would be nice to be able to configure a `nameMap` in `Dataset.getDenaturalizedDataset()` and also add it to `Client.send()` fe. to `opts` (pass to `Network._sendPDataTF`).

**Comment by PantelisGeorgiadis** [comment]
Hello @andreidubov!
Thank you for reporting this! I have create a PR (https://github.com/PantelisGeorgiadis/dcmjs-dimse/pull/48) that updated the `Network`, `Client` and `Server` classes to pass dataset read, write and nameMap options. Please review, test and let me know so I can merge it.
