### ISSUE TITLE
Asynchronous logic in handlers

### ISSUE THREAD

**Issue by hewittwill** [PantelisGeorgiadis/dcmjs-dimse#5]
Is there a current way to implement asynchronous logic (i.e. a database query) from within SCP handlers for `C-STORE` and if not, happy to look at making a PR

**Comment by PantelisGeorgiadis** [comment]
Thank you @hewittwill for you comment! There is no current way to implement asynchronous logic from within SCP handlers but I'm more than happy to consider any suggestions!

**Comment by hewittwill** [comment]
If you check out our fork [here](https://github.com/HeartLab/dcmjs-dimse/tree/will/async) you'll see our suggested implementation (just for C-STORE and C-FIND events). We called the handlers directly from the `_performDimse` function rather than using EventEmitters. This could potentially just replace the Scp class (or merge the two), and could subclass it to work with Client (I think this implementation has broken Client requests?)

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! I see your fork and I understand the changes. However, I feel that calling directly the functions defeats the purpose of class decoupling, that was the intension of the original design. Isn’t there any way to await for your business logic (e.g. database queries) within the event handlers?

**Comment by hewittwill** [comment]
Hey @PantelisGeorgiadis. Unfortunately not - await'ing for logic in the event handlers means the `e.response` is empty when the `_performDimse` tries to send the response. 

An alternative would be pulling in an asynchronous EventEmitter, like [this](https://github.com/sindresorhus/emittery)

**Comment by PantelisGeorgiadis** [comment]
I understand... Give me some time to research this and will get back to you!

**Comment by hewittwill** [comment]
This would potentially be lower impact than completely replacing the EventEmitter: [](https://github.com/sindresorhus/p-event
)

**Comment by PantelisGeorgiadis** [comment]
Hi @hewittwill! I followed your advice and now all request handlers are following an asynchronous logic. Instead of having to return something from the handlers, now you need to call the respecting callback, once you are ready. That gives your code the opportunity to execute asynchronous methods (e.g. you could wrap an async function in an IIFE).

**Comment by PantelisGeorgiadis** [comment]
Hello @hewittwill! Are you happy with the asynchronous logic implementation? Is it OK to close this?

**Comment by hewittwill** [comment]
Yes, it works well thank you!
