### ISSUE TITLE
Allow TLS ciphers to be set

### ISSUE THREAD

**Issue by richard-viney** [PantelisGeorgiadis/dcmjs-dimse#53]
Hi Pantelis,

Currently `ciphers` can't be passed through in the config when running a TLS server. Could this be added? It'd go alongside the existing settings such as `minVersion` and `maxVersion`.

Thanks!

**Comment by PantelisGeorgiadis** [comment]
Hi Richard! Is this a server-only security feature or it should be exposed for the client also?

**Comment by richard-viney** [comment]
This is valid to specify for both servers and clients that want to restrict their accepted ciphers to a specific set, e.g. those considered to be strongest.

**Comment by PantelisGeorgiadis** [comment]
Thank you Richard! Version 0.1.22 allows the `ciphers` security option to be passed.

**Comment by PantelisGeorgiadis** [comment]
Hello @richard-viney ! Closing the issue now. If you feel that we can do more on that, please reopen or create a new issue.
