### ISSUE TITLE
Feature request: Emitting event on server listening

### ISSUE THREAD

**Issue by jimOnAir** [PantelisGeorgiadis/dcmjs-dimse#55]
Hello.
I've faced the problem that I can't handle exceptions on the SCP server start properly cause it lacks a listening event. If I start the server with promise, it either never resolves or doesn't handle network error. So I've created a subclass of Server with an overriding `listen` method.
```ts 
private async listen(pacsOptions: IPacsOptions) {
    return new Promise<Server & EventEmitter>((resolve, reject) => {
      const pacsServer = (new DIMSEServer(DimseScp)) as DIMSEServer & EventEmitter;

      pacsServer.on('networkError', (error: Error) => {
        reject(error);
      });

      pacsServer.listen(pacsOptions.port, {
        ...pacsOptions.scp,
        datasetWriteOptions: { fragmentMultiframe: false },
        logCommandDatasets: false,
        logDatasets: false,
        logger: new LogService(this.pathService, DimseScp.name),
      });

    resolve(pacsServer); // Resolve before 'networkError' emitted
    });
  }
```

It would be helpful if `Server` emits some event once it is ready (propogate net.Server and tls.Server 'listening' event).

**Comment by PantelisGeorgiadis** [comment]
Thank you @jimOnAir for reporting this! Version 0.1.23 no propagates the `net.Server` and `tls.Server` `listening` event.

**Comment by PantelisGeorgiadis** [comment]
Hello @jimOnAir! Did you have the chance to test this?

**Comment by jimOnAir** [comment]
Hello @PantelisGeorgiadis . Yes, it works like a charm, thank you

**Comment by PantelisGeorgiadis** [comment]
Great to hear that!
