### ISSUE TITLE
Unable to Establish DICOM Connection with TLS Enabled

### ISSUE THREAD

**Issue by ctTushar** [PantelisGeorgiadis/dcmjs-dimse#59]
We are encountering difficulties when attempting to establish a connection with TLS support enabled. Specifically, we are facing challenges with receiving responses for operations such as cECHO (pinging the server), sending data to the Picture Archiving and Communication System (PACS) using cSTORE requests, and fetching data using cFIND requests. Surprisingly, when TLS is disabled, everything functions as expected.

Furthermore, we have observed that the cEcho call only is functioning correctly only for iOS devices but not for Android.

Here is the code snippet we are currently utilizing. We would appreciate it if you could review it and suggest any necessary corrections.

`
const dcmjsDimse = require('dcmjs-dimse');
const { Client } = require("dcmjs-dimse");
const { CEchoRequest, CFindRequets, CStoreRequest } = dcmjsDimse.requests;

const host = "17.182.121.150"; // any IP
const port =  11113; 
const callingAeTitle = "CallingAeTitle";
const calledAeTitle = "ORTHANC"; 

const opts = {
    securityOptions: {
        requestCert: true,
        rejecetUnuathorized: false,
    },
}

function echo() {
    console.log("CEcho \n--------------------------------------------------\n");
    let response = "";
    try {
        response = performCEcho(
            host,
            port,
            callingAeTitle,
            calledAeTitle,
            opts
        );

    } catch (ex) {
        console.log("echo1 Catch: ",ex);
    } finally {
        console.log("echo1 CEcho Response - " + JSON.stringify(response));
    }
}

function store() {
    console.log("CStore \n --------------------------------------------------\n");
    try {
        const response = performCStore(host, port, calledAeTitle, calledAeTitle, opts);
        console.log("store1 CStore Response" + JSON.stringify(response));
    } catch (ex) {
        console.log("store1 Catch: ",ex);
    }
}

echo();
store();`

**Comment by VamsiKWilco** [comment]
Hello,

I'm encountering an issue where the CStoreRequest functionality in dcmjs-dimse works as expected without TLS, but fails when attempting to use a TLS connection. The setup involves sending DICOM files to a PACS server configured for TLS.

Here's a simplified version of the code I'm using for the CStoreRequest:

```
const dcmjsDimse = require('dcmjs-dimse');
const { Client, CStoreRequest } = dcmjsDimse;

const sendDicom = (dicomPath, options) => {
  try {
    const { host, port, callingAeTitle, calledAeTitle } = options;
    const client = new Client();
    const request = new CStoreRequest(dicomPath);
    const otherOptions = { pduTimeout: 5 * 60 * 1000, connectTimeout: 60 * 1000 };

    // Attempt to establish a secure connection
    const attemptSecureConnection = (errorMessage) => {
      otherOptions.securityOptions = {
        rejectUnauthorized: false, // Note: This disables certificate verification for testing
        requestCert: true,
      };
      client.send(host, port, callingAeTitle, calledAeTitle, otherOptions);
    };

    client.addRequest(request);

    client.on('networkError', (e) => {
      console.log(e);
      attemptSecureConnection(e.message);
    });

    request.on('networkError', (e) => {
      console.log(e);
      attemptSecureConnection(e.message);
    });

    request.on('done', (e) => {
      console.log('done: ', e);
    });

    client.send(host, port, callingAeTitle, calledAeTitle, otherOptions);
  } catch (err) {
    console.log('Error:', err);
  }
};

```

**Environment:** Node.js environment with dcmjs-dimse version 0.1.20 (Checked with latest versions 0.1.27 as well still issue there).

**TLS Configuration:** The ORTHANC PACS server is configured to use TLS with a self signed certificate. The client attempts to connect using rejectUnauthorized: false for testing purposes, but this should ideally not be necessary in a production environment.

**Behavior:** The CStoreRequest works without TLS, but fails with a network error when attempting to use TLS.

**Additional Context:** I couldn't see any specific logs or error messages captured on server logs to help diagnose the issue.


I'm looking forward to any insights or solutions you might have. 

Thank you!

**Comment by PantelisGeorgiadis** [comment]
Hello @ctTushar and @VamsiKWilco,
Thank you for considering dcmjs-dimse for your projects!

I setup an Orthanc TLS DIMSE listener as it is described in the setup samples here: https://github.com/orthanc-server/orthanc-setup-samples/tree/master/docker/dicom-tls. Then I created a minimal C-STORE TLS scenario and noticed the following in the container logs:
```txt
2024-05-12 10:15:30 E0512 07:15:30.457941     DICOM-SERVER CommandDispatcher.cpp:284] Receiving Association failed: TLS error: wrong version number
```
It seems that orthanc requires a higher TLS version than the default used by the `tls` library. Therefore, setting `maxVersion` to `'TLSv1.2'` inside `securityOptions` made the trick!

Bellow is the full C-STORE TLS sample I used:
```js
const dcmjsDimse = require('dcmjs-dimse');
const { Client } = dcmjsDimse;
const { CStoreRequest } = dcmjsDimse.requests;

const host = '127.0.0.1';
const port = 4252;
const callingAeTitle = 'SCU';
const calledAeTitle = 'PACS_WITH_TLS';

const client = new Client();
const request = new CStoreRequest('test.dcm');
client.addRequest(request);
client.on('networkError', (e) => {
  console.log('Network error: ', e);
});
client.send(host, port, callingAeTitle, calledAeTitle, { 
    securityOptions: {
        rejectUnauthorized: false,
        requestCert: true,
        maxVersion: 'TLSv1.2'
    }
});
```

**Comment by ctTushar** [comment]
Hey @PantelisGeorgiadis, the solution you provided is now functional on the web for CStoreRequest. Could you help us adapt it for mobile? We've already integrated it into React Native for both Android and iOS without TLS, and it's working well. However, after enabling TLS, we're encountering issues with C-ECHO and C-STORE on the Android platform. On iOS, we can perform a C-ECHO call, but C-STORE isn't working.

We're utilizing the **nodejs-mobile-react-native** package to communicate with **dcmjs-dicms**. Here's the link to the package: https://github.com/Shopify/nodejs-mobile-react-native

**Comment by PantelisGeorgiadis** [comment]
Hi @ctTushar,
Unfortunately, I'm not familiar that package or the way node.js is implemented for android/iOS and, therefore, I can't be much of a help for you.

**Comment by ctTushar** [comment]
Thanks @PantelisGeorgiadis for your quick response & support.

**Comment by PantelisGeorgiadis** [comment]
Hello @ctTushar and @VamsiKWilco! I'm closing the issue now. If you feel that we can do more on that, please reopen or create a new issue.
