### ISSUE TITLE
FrameIncrementPointer Tag Not Updating Correctly in Cine Mode Multiframe

### ISSUE THREAD

**Issue by ctTushar** [PantelisGeorgiadis/dcmjs-dimse#63]
Hi @PantelisGeorgiadis,

We are trying to pass these two tags for cine mode multiframe: **FrameTimeVector** and **FrameIncrementPointer**. While we can see the video and both tags in the DICOM viewer, the value for FrameIncrementPointer is always set to (0000,0000), even when we pass a specific value. Could you please guide us on what we might be doing wrong here?

Attaching a snapshot of the output for reference.
![image](https://github.com/user-attachments/assets/59d6d277-32e0-4b81-aa73-c5aac44fec48)

`const dcmjsDimse = require('dcmjs-dimse');
const { Client } = dcmjsDimse;
const { CStoreRequest } = dcmjsDimse.requests;

const host = '127.0.0.1';
const port = 4252;
const callingAeTitle = 'SCU';
const calledAeTitle = 'PACS_WITH_TLS';

 const tags = {
    ...patientTags,
    FrameTimeVector: [32, 37, 30, 33, 35, 65, 33, 36, 63, 34, 31, 67, 35, 32, 36, 63, 32, 34, 33, 32, 67, 36, 31, 65, 34, 64, 36, 67, 37, 29, 34, 66, 32, 35, 64, 33, 36, 30, 33, 34, 65, 34, 33, 32, 33, 31, 35, 66, 34, 66, 37, 32, 64, 34, 65, 35, 31, 67, 32, 65, 33, 70, 31, 33, 31, 34, 35, 32, 34, 33, 34],
**FrameIncrementPointer: '(0018,1065)' OR  { vr: 'AT', Value: ['00181065'] } OR ['00181065'],**
}

const client = new Client();
const request = new CStoreRequest(tags);  // Notes:- this is dcm file with tags
client.addRequest(request);
client.on('networkError', (e) => {
  console.log('Network error: ', e);
});
client.send(host, port, callingAeTitle, calledAeTitle, { 
    securityOptions: {
        rejectUnauthorized: false,
        requestCert: true,
        maxVersion: 'TLSv1.2'
    }
});`

**Comment by PantelisGeorgiadis** [comment]
Hello @ctTushar!
I faced the exact same problem when I tried to create a gist that would generate Multiframe True Color Secondary Capture datasets. This is how I solved it: https://gist.github.com/PantelisGeorgiadis/476564c36b81a1698303c6309ad0cc58#file-dcmjs-sc-jpeg-gen-js-L154. Please check and let me know if this works for you.

**Comment by ctTushar** [comment]
Thanks @PantelisGeorgiadis  for quick let me try and get back to you.

**Comment by ctTushar** [comment]
You are awesome @PantelisGeorgiadis , it works thanks for quick response and solution.
<img width="912" alt="image" src="https://github.com/user-attachments/assets/bb705aaa-f863-4160-9188-b5bef3cda942">
